fix: Update PortingDeadLibs to 1.1.8 to fix NoSuchMethodError crash
CombustionEngineBE.addFluidHandler API changed in PDL 1.1.8.
Users must use PortingDeadLibs >=1.1.7